### ISSUE TITLE
searching chinese/UTF-8 failed.

### ISSUE THREAD

**Issue by wenliang** [wenliang/iceshelf#1]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 476, in format
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 15: ordinal not in range(128)
Logged from file iceshelf, line 504
Traceback (most recent call last):
  File "./iceshelf", line 507, in <module>
    if k.lower().find(cmdline.find.lower()) is not -1:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)

```

**Comment by wenliang** [comment]
fixed in 55bb4af
